import './global.css'

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body>{children}</body>
  </html>
)

export default RootLayout
